// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Models;

namespace Template.Migrations
{
    [DbContext(typeof(IspitDbContext))]
    [Migration("20220403004300_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProdavnicaSara", b =>
                {
                    b.Property<int>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<int>("SaraID")
                        .HasColumnType("int");

                    b.HasKey("ProdavnicaID", "SaraID");

                    b.HasIndex("SaraID");

                    b.ToTable("ProdavnicaSara");
                });

            modelBuilder.Entity("Template.Models.Ploca", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Duzina")
                        .HasColumnType("real")
                        .HasColumnName("Duzina");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Brojnost");

                    b.Property<bool>("Otpadna")
                        .HasColumnType("bit")
                        .HasColumnName("Otpadna");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<int?>("SaraID")
                        .HasColumnType("int");

                    b.Property<float>("Sirina")
                        .HasColumnType("real")
                        .HasColumnName("Sirina");

                    b.HasKey("ID");

                    b.HasIndex("ProdavnicaID");

                    b.HasIndex("SaraID");

                    b.ToTable("Ploca");
                });

            modelBuilder.Entity("Template.Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Prodavnica");
                });

            modelBuilder.Entity("Template.Models.Sara", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sara");
                });

            modelBuilder.Entity("ProdavnicaSara", b =>
                {
                    b.HasOne("Template.Models.Prodavnica", null)
                        .WithMany()
                        .HasForeignKey("ProdavnicaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Template.Models.Sara", null)
                        .WithMany()
                        .HasForeignKey("SaraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Template.Models.Ploca", b =>
                {
                    b.HasOne("Template.Models.Prodavnica", "Prodavnica")
                        .WithMany("Ploca")
                        .HasForeignKey("ProdavnicaID");

                    b.HasOne("Template.Models.Sara", "Sara")
                        .WithMany("Ploca")
                        .HasForeignKey("SaraID");

                    b.Navigation("Prodavnica");

                    b.Navigation("Sara");
                });

            modelBuilder.Entity("Template.Models.Prodavnica", b =>
                {
                    b.Navigation("Ploca");
                });

            modelBuilder.Entity("Template.Models.Sara", b =>
                {
                    b.Navigation("Ploca");
                });
#pragma warning restore 612, 618
        }
    }
}
